### ISSUE TITLE
Dynamic configuration (@type opensearch_dynamic) is not supported to use configurations to depend on information in messages

### ISSUE THREAD

**Issue by pratikshavyas** [fluent/fluent-plugin-opensearch#12]
There is no support available for configurations to depend on information in messages as it is available in fluent-plugin-elasticsearch (https://github.com/uken/fluent-plugin-elasticsearch/tree/v5.1.4#dynamic-configuration)

#### Steps to replicate
<match test.logging.**>
      @type copy
      <store>
          @type opensearch_dynamic
          host opensearch
          port 9200
          resurrect_after 5s
          type_name fluentd
          time_key time
          utc_index true
          time_key_exclude_timestamp true
          logstash_format true
          logstash_prefix fluentd-${tag_parts[2]}-${tag_parts[3]}
          <buffer tag, time, namespace, type>
              @type file
              path /var/log/td-agent/opensearch-buffer/test.logging.all.all
              flush_mode interval
              flush_interval 30s
              timekey 3600
              retry_forever true
              retry_max_interval 5s
              overflow_action block
              total_limit_size 1024m
         </buffer>
      </store>
    </match>

#### Expected Behavior or What you need to ask
Indices should get created in correct format with  fluentd-${tag_parts[2]}-${tag_parts[3]} after evaluating place holder values. However getting below error in the logs: "2022-01-31 08:45:42 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'opensearch_dynamic'. Run 'gem search -rd fluent-plugin' to find plugins"
...

#### Using Fluentd and OpenSearch plugin versions
Fluentd version 1.14.3
Opensearch version: 1.2.3
'fluent-plugin-opensearch' version '1.0.1'

Please suggest how to use dynamic configuration with this plugin.

**Comment by cosmo0920** [comment]
opensearch_dynamic plugin is already obsoleted and removed.

**Comment by cosmo0920** [comment]
dynamic plugin won't support anymore on OpenSearch flavor of Fluentd plugin.

**Comment by cosmo0920** [comment]
```aconf
<match test.logging.**>
      @type copy
      <store>
          @type opensearch_dynamic
          host opensearch
          port 9200
          resurrect_after 5s
          type_name fluentd
          time_key time
          utc_index true
          time_key_exclude_timestamp true
          logstash_format true
          logstash_prefix fluentd-${tag[2]}-${tag[3]}
          <buffer tag, time, namespace, type>
              @type file
              path /var/log/td-agent/opensearch-buffer/test.logging.all.all
              flush_mode interval
              flush_interval 30s
              timekey 3600
              retry_forever true
              retry_max_interval 5s
              overflow_action block
              total_limit_size 1024m
         </buffer>
      </store>
    </match>
```

would work

**Comment by pratikshavyas** [comment]
Thanks @cosmo0920 , This configuration has worked.
