### ISSUE TITLE
Impossible to connect to Opensearch inside a Docker network

### ISSUE THREAD

**Issue by rborredon** [fluent/fluent-plugin-opensearch#120]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)

#### Steps to replicate
I'm trying to do a simple test where fluentd and opensearch are in the same docker network.

The Docker compose file is:
```
services:
  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: unless-stopped
    links:
      - "opensearch"
    volumes:
      - ./fluentd/data:/fluentd/log
      - ./fluentd/conf:/fluentd/etc
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network

  opensearch: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - 'network.host: "0.0.0.0"'
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
 
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```

The fluentd config file is:
```
<source>
  @type  forward
  @id    input1
  @label @mainstream
  port  24224
</source>

<filter **>
  @type stdout
</filter>

<label @mainstream>
  <match **>
    @type opensearch
    host opensearch
    port 9200
    logstash_format false
    user admin
    password admin
    index_name fluentd.${tag}.%Y%m%d
	scheme https
	ssl_verify false
    ssl_version TLSv1_2
  </match>
</label>
```

#### Expected Behavior or What you need to ask
When I lauch the docker-compose up command, I obtain the following error:

> fluentd                | 2023-10-30 09:31:40 +0000 [warn]: #0 Could not communicate to OpenSearch, resetting connection and trying again. Connection refused - connect(2) for 172.27.0.2:9200 (Errno::ECONNREFUSED)

Of course, none of my logs are reported into Opensearch.

The complete log is :
> opensearch-node1       | Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
opensearch-node1       | **************************************************************************
opensearch-node1       | ** This tool will be deprecated in the next major release of OpenSearch **
opensearch-node1       | ** https://github.com/opensearch-project/security/issues/1755           **
opensearch-node1       | **************************************************************************
opensearch-node1       | OpenSearch Security Demo Installer
opensearch-node1       |  ** Warning: Do not use on production or public reachable systems **
opensearch-node1       | Basedir: /usr/share/opensearch
opensearch-node1       | OpenSearch install type: rpm/deb on Amazon Linux release 2023 (Amazon Linux)
opensearch-node1       | OpenSearch config dir: /usr/share/opensearch/config
opensearch-node1       | OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
opensearch-node1       | OpenSearch bin dir: /usr/share/opensearch/bin
opensearch-node1       | OpenSearch plugins dir: /usr/share/opensearch/plugins
opensearch-node1       | OpenSearch lib dir: /usr/share/opensearch/lib
opensearch-node1       | Detected OpenSearch Version: x-content-2.11.0
opensearch-node1       | Detected OpenSearch Security Version: 2.11.0.0
opensearch-node1       | /usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
opensearch-node1       | Enabling OpenSearch Security Plugin
opensearch-node1       | Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
fluentd                | 2023-10-30 09:31:37 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
fluentd                | 2023-10-30 09:31:37 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluentd' version '1.15.3'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-calyptia-monitoring' version '0.1.3'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-cmetrics' version '0.1.0'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-metrics-cmetrics' version '0.1.2'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-opensearch' version '1.1.4'
fluentd                | 2023-10-30 09:31:37 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
opensearch-node1       | WARNING: A terminally deprecated method in java.lang.System has been called
opensearch-node1       | WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/opensearch/lib/opensearch-2.11.0.jar)
opensearch-node1       | WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
opensearch-node1       | WARNING: System::setSecurityManager will be removed in a future release
fluentd                | 2023-10-30 09:31:37 +0000 [warn]: define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead
fluentd                | 2023-10-30 09:31:37 +0000 [info]: using configuration file: <ROOT>
fluentd                |   <source>
fluentd                |     @type forward
fluentd                |     @id input1
fluentd                |     @label @mainstream
fluentd                |     port 24224
fluentd                |   </source>
fluentd                |   <filter **>
fluentd                |     @type stdout
fluentd                |   </filter>
fluentd                |   <label @mainstream>
fluentd                |     <match **>
fluentd                |       @type opensearch
fluentd                |       host "opensearch"
fluentd                |       port 9200
fluentd                |       logstash_format false
fluentd                |       user "admin"
fluentd                |       password xxxxxx
fluentd                |       index_name "fluentd.${tag}.%Y%m%d"
fluentd                |       scheme https
fluentd                |       ssl_verify false
fluentd                |       ssl_version TLSv1_2
fluentd                |     </match>
fluentd                |   </label>
fluentd                | </ROOT>
fluentd                | 2023-10-30 09:31:37 +0000 [info]: starting fluentd-1.15.3 pid=7 ruby="3.0.5"
fluentd                | 2023-10-30 09:31:37 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "--config", "/fluentd/etc/fluent.conf", "--plugin", "/fluentd/plugins", "--under-supervisor"]
fluentd                | 2023-10-30 09:31:37 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
fluentd                | 2023-10-30 09:31:38 +0000 [info]: #0 init worker0 logger path=nil rotate_age=nil rotate_size=nil
fluentd                | 2023-10-30 09:31:38 +0000 [info]: adding match in @mainstream pattern="**" type="opensearch"
opensearch-node1       | WARNING: A terminally deprecated method in java.lang.System has been called
opensearch-node1       | WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/opensearch/lib/opensearch-2.11.0.jar)
opensearch-node1       | WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
opensearch-node1       | WARNING: System::setSecurityManager will be removed in a future release
opensearch-node1       | [2023-10-30T09:31:38,629][INFO ][o.o.n.Node               ] [opensearch-node1] version[2.11.0], pid[31], build[tar/4dcad6dd1fd45b6bd91f041a041829c8687278fa/2023-10-13T02:55:55.511945994Z], OS[Linux/5.15.90.1-microsoft-standard-WSL2/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.8/17.0.8+7]
opensearch-node1       | [2023-10-30T09:31:38,632][INFO ][o.o.n.Node               ] [opensearch-node1] JVM home [/usr/share/opensearch/jdk], using bundled JDK/JRE [true]
opensearch-node1       | [2023-10-30T09:31:38,632][INFO ][o.o.n.Node               ] [opensearch-node1] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-16725286551108414319, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.util.concurrent.ForkJoinPool.common.threadFactory=org.opensearch.secure_sm.SecuredForkJoinWorkerThreadFactory, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/config/opensearch-performance-analyzer/opensearch_security.policy, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, -Dopensearch.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
opensearch-node1       | [2023-10-30T09:31:39,526][INFO ][o.o.s.s.t.SSLConfig      ] [opensearch-node1] SSL dual mode is disabled
opensearch-node1       | [2023-10-30T09:31:39,526][INFO ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node1] OpenSearch Config path is /usr/share/opensearch/config
opensearch-node1       | [2023-10-30T09:31:39,739][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] JVM supports TLSv1.3
opensearch-node1       | [2023-10-30T09:31:39,741][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] Config directory is /usr/share/opensearch/config/, from there the key- and truststore files are resolved relatively
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"dataSourceManagement\" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]"}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"dataSource\" is disabled."}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:39Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.requestHeadersAllowlist\""}
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:40Z","tags":["info","plugins-system"],"pid":1,"message":"Setting up [51] plugins: [usageCollection,opensearchDashboardsUsageCollection,mapsLegacy,opensearchDashboardsLegacy,share,opensearchUiShared,embeddable,legacyExport,expressions,data,securityAnalyticsDashboards,home,apmOss,savedObjects,reportsDashboards,searchRelevanceDashboards,dashboard,mlCommonsDashboards,visualizations,visTypeVega,visTypeTimeline,visTypeTable,visAugmenter,anomalyDetectionDashboards,alertingDashboards,visTypeMarkdown,visBuilder,tileMap,regionMap,customImportMapDashboards,inputControlVis,ganttChartDashboards,visualize,queryWorkbenchDashboards,indexManagementDashboards,notificationsDashboards,management,indexPatternManagement,advancedSettings,console,dataExplorer,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,observabilityDashboards,discover,savedObjectsManagement,securityDashboards,bfetch]"}
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-node1       | [2023-10-30T09:31:40,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] TLS Transport Client Provider : JDK
opensearch-node1       | [2023-10-30T09:31:40,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] TLS Transport Server Provider : JDK
opensearch-node1       | [2023-10-30T09:31:40,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] TLS HTTP Provider             : JDK
opensearch-node1       | [2023-10-30T09:31:40,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2]
opensearch-node1       | [2023-10-30T09:31:40,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch-node1] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2]
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-node1       | [2023-10-30T09:31:40,167][INFO ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node1] Clustername: opensearch-cluster
opensearch-node1       | [2023-10-30T09:31:40,177][WARN ][o.o.s.OpenSearchSecurityPlugin] [opensearch-node1] Directory /usr/share/opensearch/config has insecure file permissions (should be 0700)
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | [agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:40Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:40Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 172.27.0.2:9200"}
opensearch-dashboards  | {"type":"log","@timestamp":"2023-10-30T09:31:40Z","tags":["error","savedobjects-service"],"pid":1,"message":"Unable to retrieve version information from OpenSearch nodes."}
fluentd                | 2023-10-30 09:31:40 +0000 [warn]: #0 Could not communicate to OpenSearch, resetting connection and trying again. Connection refused - connect(2) for 172.27.0.2:9200 (Errno::ECONNREFUSED)
fluentd                | 2023-10-30 09:31:40 +0000 [warn]: #0 Remaining retry: 14. Retry to communicate after 2 second(s).
opensearch-node1       | [2023-10-30T09:31:40,851][INFO ][o.o.p.c.c.PluginSettings ] [opensearch-node1] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
opensearch-node1       | [2023-10-30T09:31:41,292][INFO ][o.o.i.r.ReindexPlugin    ] [opensearch-node1] ReindexPlugin reloadSPI called
opensearch-node1       | [2023-10-30T09:31:41,293][INFO ][o.o.i.r.ReindexPlugin    ] [opensearch-node1] Unable to find any implementation for RemoteReindexExtension
opensearch-node1       | [2023-10-30T09:31:41,320][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node1] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
opensearch-node1       | [2023-10-30T09:31:41,344][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node1] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
opensearch-node1       | [2023-10-30T09:31:41,345][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node1] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
opensearch-node1       | [2023-10-30T09:31:41,346][INFO ][o.o.j.JobSchedulerPlugin ] [opensearch-node1] Loaded scheduler extension: scheduler_geospatial_ip2geo_datasource, index: .scheduler-geospatial-ip2geo-datasource
opensearch-node1       | [2023-10-30T09:31:41,352][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [aggs-matrix-stats]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [analysis-common]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [geo]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [ingest-common]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [ingest-geoip]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [ingest-user-agent]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [lang-expression]
opensearch-node1       | [2023-10-30T09:31:41,353][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [lang-mustache]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [lang-painless]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [mapper-extras]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [opensearch-dashboards]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [parent-join]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [percolator]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [rank-eval]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [reindex]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [repository-url]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [search-pipeline-common]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [systemd]
opensearch-node1       | [2023-10-30T09:31:41,354][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded module [transport-netty4]
opensearch-node1       | [2023-10-30T09:31:41,355][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-alerting]
opensearch-node1       | [2023-10-30T09:31:41,355][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-anomaly-detection]
opensearch-node1       | [2023-10-30T09:31:41,355][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-asynchronous-search]
opensearch-node1       | [2023-10-30T09:31:41,355][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-cross-cluster-replication]
opensearch-node1       | [2023-10-30T09:31:41,355][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-custom-codecs]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-geospatial]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-index-management]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-job-scheduler]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-knn]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-ml]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-neural-search]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-notifications]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-notifications-core]
opensearch-node1       | [2023-10-30T09:31:41,356][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-observability]
opensearch-node1       | [2023-10-30T09:31:41,357][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-performance-analyzer]
opensearch-node1       | [2023-10-30T09:31:41,357][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-reports-scheduler]
opensearch-node1       | [2023-10-30T09:31:41,357][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-security]
opensearch-node1       | [2023-10-30T09:31:41,357][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-security-analytics]
opensearch-node1       | [2023-10-30T09:31:41,357][INFO ][o.o.p.PluginsService     ] [opensearch-node1] loaded plugin [opensearch-sql]

#### Using Fluentd and OpenSearch plugin versions

* OS version: Windows 11 Family 22H2
* Docker Desktop v4.19.0
* Fluentd v1.15.3
* OpenSearch plugin version: 1.1.4

**Comment by rborredon** [comment]
I just found the issue. It was only an Opensearch configuration issue.

**Comment by UriZafrir** [comment]
but what was it?
