### ISSUE TITLE
Receiving warning "Specifying types in bulk requests is deprecated." while pushing data to opensearch

### ISSUE THREAD

**Issue by pratikshavyas** [fluent/fluent-plugin-opensearch#15]
When connected fluentd with opensearch with fluent-opensearch-plugin to push data to opensearch, receiving the below warning message frequently:

"warning: 299 OpenSearch-1.2.3-8a529d77c7432bc45b005ac1c4ba3b2741b57d4a "[types removal] Specifying types in bulk requests is deprecated."
"

#### Steps to replicate

```aconf
<match test.logging.**>
      @type copy
      <store>
          @type opensearch
          host opensearch
          port 9200
          resurrect_after 5s
          type_name fluentd
          time_key time
          utc_index true
          time_key_exclude_timestamp true
          logstash_format true
          logstash_prefix fluentd-${tag[2]}-${tag[3]}
          <buffer tag, time, namespace, type>
              @type file
              path /var/log/td-agent/opensearch-buffer/test.logging.all.all
              flush_mode interval
              flush_interval 30s
              timekey 3600
              retry_forever true
              retry_max_interval 5s
              overflow_action block
              total_limit_size 1024m
         </buffer>
      </store>
    </match>
```

#### Expected Behavior or What you need to ask
This warning should not come and data should get pushed to opensearch without any warnings.
Please explain why is this warning occuring and also how can it be resolved.

#### Using Fluentd and OpenSearch plugin versions

Fluentd version 1.14.3
Opensearch version: 1.2.3
'fluent-plugin-opensearch' version '1.0.1'

**Comment by cosmo0920** [comment]
This is because OpenSearch 1.2.3 or older version is introduced removal mapping of type.

https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0

**Comment by vitargelo** [comment]
What about this option?
https://github.com/fluent/fluent-plugin-opensearch#suppress_type_name

Looks like it is not working or for another type of warnings.

**Comment by cosmo0920** [comment]
Already supported in https://github.com/fluent/fluent-plugin-opensearch/pull/29.
