### ISSUE TITLE
Add Dynamic section to the doc

### ISSUE THREAD

**Issue by vitargan-nc** [fluent/fluent-plugin-opensearch#19]
(check apply)
- [ x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

It's not easy to configure dynamic index names. I created a working example after reading different reported issues.

**Describe the solution you'd like**

- Add **Dynamic configuration** description section based on placeholders to the readme
- Add a minimum **fluentd** version from which placeholders starts to work

Working example:

```
...
logstash_prefix ${$.kubernetes.namespace_name}-${$.kubernetes.pod_name}
...
<buffer tag, $.kubernetes.namespace_name, $.kubernetes.pod_name>
  ...
</buffer>
```

**Describe alternatives you've considered**

As an alternative feature request - add `opensearch_dynamic` @type the same way as in the elasticsearch plugin

**Comment by cosmo0920** [comment]
We won’t add it in README. This is already described in official documentation: https://docs.fluentd.org/configuration/buffer-section#placeholders
