### ISSUE TITLE
suppress_type_name is missing (even though mentioned in TOC of README)

### ISSUE THREAD

**Issue by domruf** [fluent/fluent-plugin-opensearch#26]
(check apply)
- [x ] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate
The setting suppress_type_name is listed in the TOC of the README, but there is no real entry there.
And when using it in a config file the config is invalid.

In fluent-plugin-elasticsearch on the other hand, the setting is available.
https://github.com/uken/fluent-plugin-elasticsearch#suppress_type_name

#### Expected Behavior or What you need to ask
suppress_type_name should be available

#### Using Fluentd and OpenSearch plugin versions

git main branch

**Comment by cosmo0920** [comment]
Oh, this should be forgotten to remove it from TOC.

Currently, OpenSearch does not introduce "Removal of Mapping Types" that is already introduced on the Elasticsearch.
https://github.com/opensearch-project/OpenSearch/issues/1940

**Comment by anders-swanson** [comment]
@domruf would you be able to update the TOC based on comment from @cosmo0920?

**Comment by domruf** [comment]
@cosmo0920 but opensearch already gives deprecation warnings. So shouldn't this plugin has the option to suppress the type?!
