### ISSUE TITLE
The time_key setting is not honoured when using data streams

### ISSUE THREAD

**Issue by ayaranga** [fluent/fluent-plugin-opensearch#27]
(check apply)
- [X] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate
Specify an option time_key (https://github.com/fluent/fluent-plugin-opensearch#time_key) to get the time from some other parameter but the time is not picked up from that parameter. See https://github.com/fluent/fluent-plugin-opensearch/blob/v1.0.2/lib/fluent/plugin/out_opensearch_data_stream.rb#L196 for details. 

#### Expected Behavior or What you need to ask
The time_key setting should be honoured in opensearch_data_stream similar to opensearch https://github.com/fluent/fluent-plugin-opensearch/blob/v1.0.2/lib/fluent/plugin/out_opensearch.rb#L943-L947.

#### Using Fluentd and OpenSearch plugin versions

OS version Any
Bare Metal or within Docker or Kubernetes or others? NA
Fluentd v0.12 or v0.14/v1.0
fluentd --version
fluentd 1.12.3
ES plugin 3.x.y/2.x.y or 1.x.y
fluent-plugin-opensearch 1.0.2

**Comment by cosmo0920** [comment]
OpenSearch Data Streams plugin is still experimental. Would you please send a patch for fixing this?

**Comment by ayaranga** [comment]
Thanks @cosmo0920 . When can we expect this fix to be available in release tag?

**Comment by cosmo0920** [comment]
I'd pushed the v1.0.3 release on rubygems today.
