### ISSUE TITLE
buffer option queued_chunks_limit_size does not work as documented

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-plugin-opensearch#34]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate

Testing with the following match statement
```
<match **>
    @id out_opensearch
    @type opensearch
    scheme https
    ssl_verify true
    host XXXHOSTXXX
    port XXXPORTXXX
    user XXXUSERXXX
    password XXXPASSWORDXXX
    target_index_key @target_index
    remove_keys @target_index
    compression_level default_compression
    <buffer tag>
      @type file
      #path set via root_dir (for multi worker)
      queued_chunks_limit_size 2
      compress gzip
      flush_interval 1s
      overflow_action block
      retry_type periodic
      retry_forever true
      retry_wait 5s
    </buffer>
</match>
```

#### Expected Behavior or What you need to ask

When OpenSearch service is unavailable,  the queued_chunks_limit_size buffer option does not work as documented:
https://docs.fluentd.org/configuration/buffer-section#buffering-parameters

After each worker stores 2 chunks to disk )in this example), documentation implies that queuing additional chucks would be limited.  

Testing with in_http and we do not see the overflow_action block go into effect.

Not sure this issue is limited to the OpenSearch Output plugin

#### Using Fluentd and OpenSearch plugin versions

OS version: Docker image built off ghcr.io/calyptia/fluentd:v1.14.5-debian-1.0
Bare Metal or within Docker or Kubernetes or others?: Docker image built off ghcr.io/calyptia/fluentd:v1.14.5-debian-1.0
Fluentd v1.0 or later: 1.14.5
OpenSearch plugin version: fluent-plugin-opensearch version 1.0.2

**Comment by cosmo0920** [comment]
> When OpenSearch service is unavailable, the queued_chunks_limit_size buffer option does not work as documented:
> https://docs.fluentd.org/configuration/buffer-section#buffering-parameters

Hmm..., it's curious....

Fluentd Output plugin should work as following description in official documentation:
https://docs.fluentd.org/output#overview

In general, output plugin will pile up ingested events into `stage` phase and then move out them into `queue`. This parameter limits the number of queued events.

**Comment by ryn9** [comment]
@cosmo0920 - please close. The docs regarding queued_chunks_limit_size were confusing, but I most certainly did not understand what what it was doing. I have a better understanding now.

**Comment by cosmo0920** [comment]
Sure. Let's close this issue.
