### ISSUE TITLE
Placeholders custom key with nested value

### ISSUE THREAD

**Issue by robinAwallace** [fluent/fluent-plugin-opensearch#51]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate

Hello, 

There does not seem to be a way to access nested values when working with placeholders and custom keys. There are no examples of this scenario in the [docs](https://github.com/fluent/fluent-plugin-opensearch#custom-key). 

If I have this log I expect to be able to access `namespace_name` with `kubernetes.namespace_name` or `${record['kubernetes']['namespace_name']}` as you do for the filter `record_transformer`. But neither of these worked.
```
{
   ...
   "kubernetes": {
      "container_name": "calico-node",
      "namespace_name": "kube-system",
      ...
    },
    ...
}
```
```
<match kubernetes.**>
  @type opensearch
  logstash_format
  logstash_prefix ${kubernetes.namespace_name} or ${record['kubernetes']['namespace_name']} # => e.g.) kube-system
  <buffer tag, kubernetes.namespace_name>
    @type memory
  </buffer>
  # <snip>
</match>
```

#### Expected Behavior or What you need to ask

Expected to be able to use nested value for `logstash_prefix`

#### Using Fluentd and OpenSearch plugin versions

* Kubernetes
* Fluentd v1.14.6
* OpenSearch plugin v1.0.2

**Comment by cosmo0920** [comment]
```aconf
<match kubernetes.**>
  @type opensearch
  logstash_format
  logstash_prefix ${$.kubernetes.namespace_name}
  <buffer tag, $.kubernetes.namespace_name>
    @type memory
  </buffer>
  # <snip>
</match>
```

should work.

**Comment by robinAwallace** [comment]
@cosmo0920 It worked, thank you!

**Comment by cosmo0920** [comment]
@pluhmen This notation is built by record accessor that is one of the plugin helper: https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-record_accessor#syntax

That is the minimum knowledge of needed to know how to use.
