### ISSUE TITLE
@type opensearch doesnt work until we change to opensearch_data_stream

### ISSUE THREAD

**Issue by affansyed** [fluent/fluent-plugin-opensearch#59]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [x] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate

Plugin does not work with @type opensearch works, but using    @type opensearch_data_stream
sends data to the opensearch server

#### Expected Behavior or What you need to ask
the following configuration was used based on the blog here: 
alongside extensive search around on the internet  

https://pastebin.com/bdbTWMUt

However simply using the data_stream, the setup was working

https://pastebin.com/aze7MdYt
...

#### Using Fluentd and OpenSearch plugin versions

* OS version: 
Oracle Linux
* Bare Metal or within Docker or Kubernetes or others?
K8s deployment

* Fluentd v1.0 or later 
"fluentd", "1.14.6"
* OpenSearch plugin version 
*fluent-plugin-opensearch 1.0.5

**Comment by cosmo0920** [comment]
Did you use this helm chart to deploy OpenSearch application into your k8s environment?
https://github.com/opensearch-project/helm-charts

If so, OpenSearch containers should launch as OpenSearch 2.0.0-rc or 2.0.0.
And I found that `suppress_type_name` shouldn't work as intended. I'll fix it soon.

**Comment by cosmo0920** [comment]
@affansyed Could you use the below configuration and OpenSearch plugin v1.0.6?
Fluentd's configuration is case-sensitive and there is no `Snake_Case` style configuration parameters in this plugin.

```aconf
    <label @OUTPUT>
      <match **>
        @type opensearch
        @id out_os
        @log_level info
        host "opensearch-cluster-master.default.svc.cluster.local"
        port "9200"
        scheme "https"
        ssl_verify "false"
        suppress_type_name true # Use snake_case without capital cases.
        retry_limit False
        reconnect_on_error true
        reload_on_failure true
        include_timestamp true
        index_name demo-test
        user admin
        password admin
      </match>
   </label>
```

**Comment by affansyed** [comment]
thank you.. this change worked.
